### PR TITLE
Switchable Dark Mode

### PR DESCRIPTION
**Pull request by rdavydov**
Checkbox on the central panel toggles dark mode: makes all the UI elements dark with the light text and applies the dark "Monokai" theme to all CodeMirror editors.

### CODE REVIEW

**Comment by rdavydov** [comment]
Demo: https://rdavydov.github.io/jwt-webtool/

**Comment by rdavydov** [comment]
Also it saves this option to the local storage, so the dark mode state is remembered in the browser on the next visit.

**Comment by DinoChiesa** [comment]
Cool!

**Comment by DinoChiesa** [comment]
THANK YOU for this cool PR. 

Unfortunately I had made some changes in the tool afterwards, so I could not merge the PR as is.  But I incorporated your changes in the latest. See [this commit](https://github.com/DinoChiesa/jwt-webtool/commit/79908569d10a2f45182159e5ba4187c5b25df25e).

**Comment by rdavydov** [comment]
@DinoChiesa

Hi Dino Chiesa,

I hope you're doing well.

I'm reaching out regarding this pull request I submitted on Feb 3 for the switchable dark mode feature. I noticed that the pull request was closed on Apr 26, and the feature was subsequently added to the tool without any mention of my contribution.

I understand that changes might have been made which led to conflicts, making it challenging to merge the pull request directly. However, I believe that acknowledging contributions is important in fostering a collaborative and respectful open-source community.

Would it be possible to credit my contribution to the switchable dark mode feature in the project? It could be as simple as mentioning my GitHub handle @rdavydov in the commit message or the project’s acknowledgments.

Thank you for considering this request. I appreciate your understanding and look forward to your response.

Best regards,
Roman Davydov
@rdavydov

**Pull request closed without merging**
